root: true

env:
  node: true

extends:
  - "plugin:vue/recommended"
  - "@vue/airbnb"

parserOptions:
  parser: babel-eslint

rules:
  # General
  no-tabs: 0
  object-curly-spacing:
    - 2
    - always
    - objectsInObjects: false

  # Vue
  indent: 0
  vue/html-closing-bracket-newline:
    - 2
    - singleline: never
      multiline: always
  vue/html-indent:
    - 2
    - tab
  vue/script-indent:
    - 2
    - tab
    - baseIndent: 1
      switchCase: 1

  # Project-specific rules
  no-console: 0
