root: true

env:
  node: true

extends:
  - "plugin:vue/recommended"
  - "@vue/airbnb"

parserOptions:
  parser: babel-eslint

rules:
  # General
  comma-dangle:
    - 2
    - never
  no-tabs: 0
  object-curly-newline: 0
  object-curly-spacing:
    - 2
    - always
    - objectsInObjects: false

  # Vue
  indent: 0
  vue/html-indent:
    - 2
    - tab
  vue/script-indent:
    - 2
    - tab
    - baseIndent: 1
      switchCase: 1
